<?php

namespace common\models;

use \common\models\base\InvoicePayment as BaseInvoicePayment;

/**
 * This is the model class for table "invoice_payment".
 */
class InvoicePayment extends BaseInvoicePayment
{

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }
}
