<?php

namespace common\models;

use common\models\base\InvoiceStatus as BaseInvoiceStatus;

/**
 * This is the model class for table "invoice_status".
 */
class InvoiceStatus extends BaseInvoiceStatus
{
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

}
