<?php

namespace common\models;

use common\models\base\PaypalTransaction as BasePaypalTransaction;

/**
 * This is the model class for table "paypal_transaction".
 */
class PaypalTransaction extends BasePaypalTransaction
{
    public function behaviors()
    {
        $behaviors = parent::behaviors();

        $behaviors['slug']['attribute'] = 'payment_id';

        return $behaviors;
    }

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

}
